---
title: "BasicBar"
author: "Paul Guerra"
date: "March 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(jsonlite)
library(curl)
library(dplyr)
```
## Pull data from the STC website using the table number (in this case national crop supply and disposition 32100013)
```{r} 
stc_table_num <- "32100013"
stc_pull <- fromJSON(curl(sprintf("https://www150.statcan.gc.ca/t1/wds/rest/getFullTableDownloadCSV/%s/en", stc_table_num)))

temp <- tempfile()
download.file(stc_pull$object, temp)
stc_data <- read.csv(unz(temp, sprintf("%s.csv", stc_table_num)))
unlink(temp)
rm(stc_pull)

```

# Select the relevant columns from the table and rename
```{r}
crop_s_d <- select(stc_data, date = REF_DATE, crop = Type.of.crop, s_d = Supply.and.disposition.of.grains,  VALUE)

```

# Use unique() to see all the crop types under the crop column
```{r}
crop_types <- unique(crop_s_d$crop)

f_crop_s_d <- filter(crop_s_d, s_d == "Total ending stocks")
```

# Group by crop type and sum 
```{r}
crop_totals <- group_by(f_crop_s_d, crop)

sum_crop_total <- sum(f_crop_s_d$VALUE, na.rm = TRUE)
sum_croptype_totals <- summarise(crop_totals, crop_vol = sum(VALUE, na.rm = TRUE), crop_proportion = sum(VALUE, na.rm = TRUE) / sum_crop_total)
sum_croptype_totals

```

